export const battlesuitStrengths = [
  { icon: 'feature-icons/physical', value: 'physical', label: 'Physical' },
  { icon: 'feature-icons/fire-dmg', value: 'fire-dmg', label: 'Fire DMG' },
  { icon: 'feature-icons/ice-dmg', value: 'ice-dmg', label: 'Ice DMG' },
  {
    icon: 'feature-icons/lightning-dmg',
    value: 'lightning-dmg',
    label: 'Lightning DMG',
  },
  { icon: 'feature-icons/freeze', value: 'freeze', label: 'Freeze' },
  { icon: 'feature-icons/paralyze', value: 'paralyze', label: 'Paralyze' },
  { icon: 'feature-icons/stun', value: 'stun', label: 'Stun' },
  { icon: 'feature-icons/ignite', value: 'ignite', label: 'Ignite' },
  { icon: 'feature-icons/bleed', value: 'bleed', label: 'Bleed' },
  { icon: 'feature-icons/heavy-atk', value: 'heavy-atk', label: 'heavy-atk' },
  { icon: 'feature-icons/weaken', value: 'weaken', label: 'Weaken' },
  { icon: 'feature-icons/impair', value: 'impair', label: 'Impair' },
  {
    icon: 'feature-icons/time-mastery',
    value: 'time mastery',
    label: 'Time Mastery',
  },
  { icon: 'feature-icons/gather', value: 'gather', label: 'Gather' },
  { icon: 'feature-icons/heal', value: 'heal', label: 'Heal' },
  { icon: 'feature-icons/fast-atk', value: 'fast atk', label: 'Fast ATK' },
  { icon: 'feature-icons/burst', value: 'burst', label: 'Burst' },
  { icon: 'feature-icons/aerial', value: 'aerial', label: 'Aerial' },
]
